### ISSUE TITLE
(Unsolicited) General Feedback

### ISSUE THREAD

**Issue by mattt** [christoph-jerolimov/AFCalendarRequestOperation#5]
Howdy @jerolimov!

I saw your library come up on Twitter, and thought I'd take a second to say thanks for making this extension. Nice work!

If you don't mind me making a few unsolicited suggestions, here were some initial thoughts I had with the library.
- It'd be really cool if you could use EventKit (`EKEvent`, et al.) as the data model to encapsulate the parsed calendar information. I'm not entirely sure about the logistics of creating events outside of the context of adding them immediately to the calendar, but it'd be a huge win to be able to re-purpose the wisdom Apple put into the design of those classes.
- Minor semantic nitpick: your operation class should probably be named `AFiCalendarRequestOperation` (you could take out that lowercase "i").
- Another one: In the request operation class, the property should be named `responseCalendar`, to fit the convention.
- I'd like to see a class constructor similar to `AFJSONRequestOperation + JSONRequestOperationWithRequest:success:failure:`
- You probably don't need to have `AFCalendarClient`, since `AFHTTPClient`s can register the request operation class and have that automatically parsed (just like JSON or XML, which don't need their own client classes)
- I generally like to reduce the number of files by consolidating highly-coupled and internal objects into a single file. You could do the same by defining `AFCalendarModel` in the request operation `.h` (or eliminating it altogether by using EventKit), and making `AFCalendarParser` private by defining and implementing in the request operation `.m` (like how `AFHTTPClient` has internal classes for the multipart form builder stream).

Anyway, thanks again for taking the time to make something cool with AFNetworking. Looking forward to seeing where you take this library.

**Comment by christoph-jerolimov** [comment]
@mattt You also recommend to rename the whole project to `AFCalendarRequestOperation`, or?

**Comment by mattt** [comment]
@jerolimov Yeah, that would better-fit the convention of other extensions. `AFCalendarRequestOperation` is really where the meat is anyway :)
